export const FETCH_CLIENT_TRANSACTIONS = "FETCH_CLIENT_TRANSACTIONS";
export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
export const FETCH_CLIENT_TRANSACTIONS_BY_ID =
  "FETCH_CLIENT_TRANSACTIONS_BY_ID";
